### ISSUE TITLE
Click if available thows Not clickable exception

### ISSUE THREAD

**Issue by pvreeuwijk** [fhoeben/hsac-fitnesse-fixtures#208] opened 2018-05-16 09:37 UTC
The method clickifavailable aims to avoid thowing an exception when the element is not visible.
This works fine when the element is not present in the page.
In our application, a modal is always present in the page, but not visible.
In this situation the method clickifavailable thowns an elementnotclicable at point x,y and our test fails.

suggested behaviour: return false

**Comment by fhoeben** [comment] 2018-05-19 15:42
You are right about the intended behaviour.

Are you using the latest version of the fixtures and which browser? 
I've been unable to reproduce the behaviour you describe with chrome. There is a test in the acceptance tests that aims verify no exception is thrown (although it did not explicitly do an 'click if available', I've added that in the master branch): HsacAcceptanceTests.SlimTests.BrowserTest.ClickTemporarilyCoveredLinkTest

Can you provide some more details (and HTML) allowing me to reproduce?

**Comment by fhoeben** [comment] 2018-08-10 15:55
Closing since no follow up to my request for sample HTML

**Closed by fhoeben** 2018-08-10 15:55 UTC
