### ISSUE TITLE
Calculation in FitNesse

### ISSUE THREAD

**Issue by ybermejo** [fhoeben/hsac-fitnesse-fixtures#226] opened 2018-08-07 08:45 UTC
Hi,
Is there a way or a fixture that will calculate symbols (e.g. $var) and pass the result to another symbol? I'm trying to use the "Expressions using the mark up(${=exp=})" but when I add the symbol in the expression, it gets an invalid expression error and not calculate the expression. Thank for help in advance.

**Comment by tcnh** [comment] 2018-08-08 11:12
You can use script language fixture for this.

Or -if you're more adventurous- use my bootlegged fitnesse version that
incorporates https://github.com/unclebob/fitnesse/pull/1123 which allows
you to do $`expr` anywhere when using Slim.

See:
https://search.maven.org/#artifactdetails%7Ccom.github.tcnh%7Cfitnesse%7C20180425%7Cjar


Op di 7 aug. 2018 10:45 schreef ybermejo <notifications@github.com>:

**Comment by ybermejo** [comment] 2018-08-08 12:09
Hi @tcnh ,
If I'm going to use your bootlegged fitnesse, how would I implement that in my current fitnesse project? Cause I'm short in time to create a script for this function, or is there any existing script or fixture that I can use? Thanks for responding.

**Comment by tcnh** [comment] 2018-08-08 12:45
Just replace the fitnesse dependency in your pom. (Assuming you use a maven
project) Replace package org.fitnesse with com.github.tcnh and use version
20180425.

If you're not using maven, download the standalone jar from maven central
and replace fitnesse-standalone.jar in your project with the downloaded jar
file.

**Comment by tcnh** [comment] 2018-08-08 14:40
If you downloaded the standalone hsac zip file, the folder you have
extracted to contains a file called fitnesse-standalone.jar. Replace that
file with the newer fitnesse-standalone.jar from maven central.

This should have no impact on any existing scripts.

Op wo 8 aug. 2018 15:21 schreef ybermejo <notifications@github.com>:

**Comment by ybermejo** [comment] 2018-08-08 15:15
Yeah. Is this the right link? 
http://repo1.maven.org/maven2/com/github/tcnh/fitnesse/20180425/fitnesse-20180425-standalone.jar
Thanks man!

**Comment by boredland** [comment] 2018-08-08 15:57
Either way: can't we include this here?

**Comment by ybermejo** [comment] 2018-08-08 16:35
Hi @tcnh ,

It's working now. But I have questions:
*2nd row - why I'm getting null?
*5th and 6th row - it just concatenate the values and not adding it, why?
 please see attached image.
![image](https://user-images.githubusercontent.com/40356873/43850800-82208ff0-9b6b-11e8-82b1-9346604f49b0.png)

**Comment by tcnh** [comment] 2018-08-08 18:09
I have no way of reproducing now (on a camping trip in France), but I think
using array as the name of a variable will produce unwanted results in
java. Try if it works with $myArray as the car name.

The concatenation happens because string fixture's value of will set the
variable to a Strong value of "2" in line 3 where you are expecting a
double or int. (2.0 or 2 instead of "2")

**Comment by ybermejo** [comment] 2018-08-08 18:18
It still not working even i change the symbol name. 
I'm actually expecting both data types. How will the system not treat the value as string?

**Comment by tcnh** [comment] 2018-08-08 18:25
On the first line you're missing a !
Hashtables are defined as follows: !{key:Val}



If you can't be sure of the data type you receive, you'll have to manually
parse them in the expression. parseInt(strVal) or parseFloat(strVal) should
convert to integer or decimal.


>

**Comment by ybermejo** [comment] 2018-08-08 19:08
Thanks man, all are solved. Follow up question, the answer for arithmetic operations are always double. How can i treat that as int? I already parsed the answer but still has ".0". I can remove that by using a regex but is there a simpler way in removing that?

**Comment by tcnh** [comment] 2018-08-08 20:01
I think fitnesse (or slim) outputs numbers with a decimal. You could try
calling .toFixed() in your expression, but I haven't tried that. Another
workaround could be to use an expression in your expected outcome as well.

**Comment by ybermejo** [comment] 2018-08-08 20:06
Okay, thanks again for helping me out.

**Comment by tcnh** [comment] 2018-08-08 21:28
Hard to debug with just that message :)
Try setting slim port to auto uning: !define slim.port {0} if you didn't
already do that.

>
>

**Comment by ybermejo** [comment] 2018-08-09 08:01
This error log was populated in my fitnesse folder. My machine is 64bit, how am i going to resolve this issue? Thanks.
![image](https://user-images.githubusercontent.com/40356873/43886172-87c658b8-9bed-11e8-8601-1cfe50f84db0.png)

**Comment by fhoeben** [comment] 2018-08-10 15:41
for the error message you created a separate issue, which I answered and closed. Closing this issue also because I believe the original issue was also solved.

**Closed by fhoeben** 2018-08-10 15:41 UTC
